- name: Create {{version}} folder
  file:
    path: '{{share_dir}}/protobuf/{{version}}'
    state: directory
  tags: [protobuf]

- name: Fetch and unpack {{version}}
  unarchive:
    src: https://github.com/google/protobuf/releases/download/v{{version}}/protoc-{{version}}-linux-x86_64.zip
    dest: '{{share_dir}}/protobuf/{{version}}'
    remote_src: yes
    creates: '{{share_dir}}/protobuf/{{version}}/bin/protoc'
  tags: [protobuf]

- name: Add startup config
  copy:
    content: export PATH={{share_dir}}/protobuf/{{version}}/bin:$PATH
    dest: '{{startup_dir}}/protobuf'
  tags: [protobuf]
