#!/usr/bin/env bash

set -eu

selected_key=$(\
  cat ~/.clipmenu/*.json \
    | jq -r 'keys | .[]' \
    | pmenu)

selected_value=$(\
  cat ~/.clipmenu/*.json \
    | jq -rs "add | .[\"${selected_key}\"]")

xclip -i -selection clipboard <<< "$selected_value"
