#!/usr/bin/env bash

script_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

ansible-playbook \
  -i "${script_dir}"/../../hosts \
  --extra-vars @"${script_dir}"/../../themes/dark.yml \
  --extra-vars @"${script_dir}"/../../vars.yml \
  "$@" \
  "${script_dir}"/../../odbox.yml
