#!/usr/bin/env bash
#
# Set a keyboard layout from ~/.xkb

set -e

usage() {
  {
  echo "Usage: setxkb <layout-name>"
  } 1>&2
}

layout_name=$1

[[ $layout_name ]] || { usage; exit 1; }

setxkbmap -I "$HOME"/.xkb "$layout_name" -print \
  | xkbcomp -I"$HOME"/.xkb - "$DISPLAY" 2>/dev/null
