#!/usr/bin/env bash

set -eu

session_name=$1

bash_cmd="\
  tmux -2 -q has-session -t ${session_name} \
  && exec tmux -2 attach-session -d -t ${session_name} \
  || exec tmux -2 new-session -s ${session_name}"

urxvtc -name "${session_name}" -e bash -c "${bash_cmd}"
