#- import_playbook: '{{playbook_dir}}/einride/devtools.yml'

- hosts: [localhost]
  connection: local
  vars_files:
    - '{{playbook_dir}}/einride/vars/dirs.yml'
    - '{{playbook_dir}}/einride/vars/user.yml'

  tasks:
    - import_role:
        name: bash
      vars:
        shfmt_version: 2.6.4

    - import_role:
        name: desktop
      vars:
        fzf_version: 0.17.4

    - import_role:
        name: git

    - import_role:
        name: haskell

    - import_role:
        name: iosevka
      vars:
        version: 1.14.3

    - import_role:
        name: neovim

    - import_role:
        name: spotify

    - import_role:
        name: tmux
