- import_playbook: "{{playbook_dir}}/einride/devtools.yml"

- hosts: [localhost]
  connection: local
  vars_files:
    - "{{playbook_dir}}/einride/vars/dirs.yml"
    - "{{playbook_dir}}/einride/vars/user.yml"

  tasks:
    - import_role:
        name: bash

    - import_role:
        name: desktop

    - import_role:
        name: dropbox

    - import_role:
        name: keepassxc

    - import_role:
        name: fzf
      vars:
        version: 0.27.2

    - import_role:
        name: ripgrep
      vars:
        version: 13.0.0

    - import_role:
        name: delta
      vars:
        version: 0.8.1

    - import_role:
        name: git

    - import_role:
        name: iosevka
      vars:
        version: 7.2.0

    - import_role:
        name: neovim

    - import_role:
        name: spotify

    - import_role:
        name: tmux

    - import_role:
        name: webstorm
      vars:
        version: 2021.1.2
