- import_playbook: "{{playbook_dir}}/einride/devtools.yml"

- hosts: [localhost]
  connection: local
  vars_files:
    - "{{playbook_dir}}/einride/vars/dirs.yml"
    - "{{playbook_dir}}/einride/vars/user.yml"

  tasks:
    - import_role:
        name: bash

    - import_role:
        name: desktop

    - import_role:
        name: dropbox

    - import_role:
        name: keepassxc

    - import_role:
        name: fzf
      vars:
        version: 0.25.0

    - import_role:
        name: delta
      vars:
        version: 0.5.0

    - import_role:
        name: git

    - import_role:
        name: iosevka
      vars:
        version: 4.3.0

    - import_role:
        name: neovim

    - import_role:
        name: spotify

    - import_role:
        name: tmux

    - import_role:
        name: webstorm
      vars:
        version: 2020.3

    - import_role:
        name: pycharm
      vars:
        version: 2020.3
