- import_playbook: "{{playbook_dir}}/einride/devtools.yml"

- hosts: [localhost]
  connection: local
  vars_files:
    - "{{playbook_dir}}/einride/vars/dirs.yml"
    - "{{playbook_dir}}/einride/vars/user.yml"

  tasks:
    - import_role:
        name: bash

    - import_role:
        name: desktop
      vars:
        fzf_version: 0.21.1

    - import_role:
        name: dropbox

    - import_role:
        name: git

    - import_role:
        name: iosevka
      vars:
        version: 3.0.0-rc.6

    - import_role:
        name: neovim

    - import_role:
        name: spotify

    - import_role:
        name: tmux
