#!/usr/bin/env bash

script_dir="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

ansible-playbook \
  -i localhost, \
  -c local \
  --extra-vars @"${script_dir}"/vars.json \
  "$@" \
  "${script_dir}"/pbox.yaml
