- hosts: all

  tasks:
    - name: Add config lines
      become: yes
      become_user: root
      lineinfile:
        dest: '/etc/{{item.file}}'
        line: '{{item.line}}'
        state: present
        create: yes
      with_items:
        - {file: vconsole.conf, line: FONT=Lat2-Terminus16}
        - {file: vconsole.conf, line: KEYMAP=dvorak}
        - {file: locale.conf, line: LANG=en_US.UTF-8}
      tags: [config]

    - name: Render config templates
      become: yes
      become_user: root
      template:
        src: 'etc/{{item}}.j2'
        dest: /etc/{{item}}
      with_items:
        - hostname
      tags: [config]

    - name: Create dotfolders
      file:
        path: ~/.{{item}}
        state: directory
      with_items:
        - bin
        - clipmenu
        - xmonad
        - bash.d
        - Xresources.d
        - xkb/symbols
        - config/nvim/autoload
        - config/dwb
        - urxvt/ext
        # IntelliJ
        - IdeaIC2016.3/config/colors
        - IdeaIC2016.3/config/options
      tags: [dotfolders]

    - name: Install dotfiles
      copy:
        src: dotfiles/{{item}}
        dest: ~/.{{item}}
      with_items:
        - Xresources
        - tmux.conf
        - xmonad/xmonad.hs
        - xkb/symbols/poskeys
        - xinitrc
        - gemrc
        - psqlrc
        - config/nvim/init.vim
        - config/dwb/keys
        - bashrc
        - inputrc
        - bash.d/prompt.bash
        - urxvt/ext/clipboard
        # IntelliJ
        - IdeaIC2016.3/config/disabled_plugins.txt
        - IdeaIC2016.3/config/colors/poscar.icls
        - IdeaIC2016.3/config/options/colors.scheme.xml
        - IdeaIC2016.3/config/options/editor.codeinsight.xml
        - IdeaIC2016.3/config/options/editor.xml
        - IdeaIC2016.3/config/options/parameter.hints.xml
        - IdeaIC2016.3/config/options/ui.lnf.xml
      tags: [dotfiles]

    - name: Render dotfile templates
      template:
        src: '{{item}}.j2'
        dest: ~/.{{item}}
      with_items:
        - Xresources.d/rxvt-unicode
        - bash.d/theme.bash
        - gitconfig
        - config/dwb/settings
      tags: [dotfiles]

    - name: Install scripts into ~/.bin
      copy:
        src: scripts/{{item}}
        dest: ~/.bin/{{item}}
        mode: 0755
      with_items:
        - print-bash-colors
        - print-tmux-colors
        - clipmenu
        - tmuxargs
        - tmuxssh
        - ttymux
        - setxkb
        - dmenu
        - mvn-autoenforce
      tags: [scripts]

    - name: Symlink pbox script
      file:
        src: '{{playbook_dir}}/files/scripts/pbox'
        dest: ~/.bin/pbox
        state: link
      tags: [scripts]

    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/hosts.yml

    - name: Set group ownership of /media to users
      become: yes
      become_user: root
      file:
        path: /media
        state: directory
        group: users 
      tags: [media]

    - name: Start services
      become: yes
      become_user: root
      systemd:
        name: '{{item}}'
        enabled: yes
      with_items:
        - dhcpcd
        - vboxservice
        - docker
      tags: [services]

    - name: Add user to groups
      become: yes
      become_user: root
      user:
        name: '{{username}}'
        groups: '{{item}}'
        append: yes
      with_items:
        - docker
        - vboxsf
      tags: [groups]
