- name: Install packages
  become: yes
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - bspwm
    - sxhkd
    - tmux
    - rxvt-unicode
    - keepassxc
    - xclip
    - xcape
  tags: [desktop]

- name: Create dotfolders
  file:
    path: ~/.{{item}}
    state: directory
  loop:
    - urxvt/ext
    - config/sxhkd
    - config/bspwm
    - config/rofi
  tags: [desktop]

- name: Install dotfiles
  copy:
    src: '{{item}}'
    dest: ~/.{{item}}
  loop:
    - Xresources
    - urxvt/ext/clipboard
    - config/sxhkd/sxhkdrc
    - config/rofi/config
  tags: [desktop]

- name: Install scripts
  copy:
    src: '{{item}}'
    dest: '{{bin_dir}}/{{item}}'
    mode: 0755
  loop:
    - urxvtmux
  tags: [desktop]

- name: Install global config files
  become: yes
  copy:
    src: '{{item}}'
    dest: /{{item}}
  loop:
    - usr/share/X11/xkb/symbols/custom
  tags: [desktop]

- name: Add startup config
  copy:
    content: |
      export _JAVA_AWT_WM_NONREPARENTING=1
      export FZF_DEFAULT_OPTS="
        --color fg:10,bg:-1,hl:4,fg+:12,bg+:-1,hl+:4
        --color info:12,prompt:10,pointer:12,marker:12,spinner:12"
    dest: '{{startup_dir}}/desktop'
  tags: [desktop]

- name: Create fzf {{fzf_version}} dir
  file:
    path: '{{share_dir}}/fzf/{{fzf_version}}'
    state: directory
  tags: [fzf]

- name: Install fzf
  unarchive:
    src: https://github.com/junegunn/fzf-bin/releases/download/{{fzf_version}}/fzf-{{fzf_version}}-linux_amd64.tgz
    dest: '{{share_dir}}/fzf/{{fzf_version}}'
    remote_src: yes
    creates: '{{share_dir}}/fzf/{{fzf_version}}/fzf'
  tags: [fzf]

- name: Symlink fzf {{fzf_version}} binary
  file:
    src: '{{share_dir}}/fzf/{{fzf_version}}/fzf'
    dest: '{{bin_dir}}/fzf'
    state: link
  tags: [fzf]
