- name: Install packages
  become: yes
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - xmonad
    - libghc-xmonad-contrib-dev
    # Required by xmonad.hs
    - rxvt-unicode
    - keepassxc
    - xclip
    - tmux
    # Required by keyboard
    - xcape
    # KDE
    - dolphin-plugins
  tags: [desktop]

- name: Create dotfolders
  file:
    path: ~/.{{item}}
    state: directory
  loop:
    - urxvt/ext
    - xmonad
  tags: [desktop]

- name: Install dotfiles
  copy:
    src: '{{item}}'
    dest: ~/.{{item}}
  loop:
    - Xresources
    - urxvt/ext/clipboard
    - xmonad/xmonad.hs
  tags: [desktop]

- name: Install scripts
  copy:
    src: '{{item}}'
    dest: '{{bin_dir}}/{{item}}'
    mode: 0755
  loop:
    - init-urxvt
    - init-keyboard
    - urxvtmux
  tags: [desktop]

- name: Install shared files
  copy:
    src: '{{item}}'
    dest: '{{share_dir}}/{{item}}'
  loop:
    - rofi-theme.rasi
  tags: [desktop]

- name: Install config files
  become: yes
  copy:
    src: '{{item}}'
    dest: /{{item}}
  loop:
    - usr/share/X11/xkb/symbols/custom
  tags: [desktop]

- name: Add startup config
  copy:
    content: |
      export _JAVA_AWT_WM_NONREPARENTING=1
      init-urxvt
      init-keyboard
    dest: '{{startup_dir}}/desktop'
  tags: [desktop]

- name: Add themed rofi script
  copy:
    content: |
      /usr/bin/rofi -theme {{share_dir}}/rofi-theme.rasi "$@"
    dest: '{{bin_dir}}/rofi'
    mode: 0755
  tags: [desktop]
