#!/usr/bin/env bash

export TERM='screen-256color'
export EDITOR='vim'
export HISTCONTROL='ignoredups'
export HISTSIZE=100000
unset MAILCHECK

export GREP_COLOR='34'

export LS_COLORS='di=1;94'

export PYTHONDONTWRITEBYTECODE='1'

shopt -s histappend
shopt -s extglob
bind Space:magic-space

stty -ixon # disable XON/XOFF flow control

alias xi='xclip -selection clipboard -i'
alias xo='xclip -selection clipboard -o'

source ~/.bash.d/theme.bash
source ~/.bash.d/prompt.bash
source /usr/share/bash-completion/bash_completion

if [[ $OSTYPE =~ ^linux ]]; then
  alias ls='ls --color=auto --classify'
fi

export PATH=~/.bin:$PATH
export PATH=~/.cabal/bin:$PATH

if [[ -d ~/software/google-cloud-sdk/google-cloud-sdk ]]; then
  source ~/software/google-cloud-sdk/google-cloud-sdk/path.bash.inc
  source ~/software/google-cloud-sdk/google-cloud-sdk/completion.bash.inc
  if [[ -f ~/.gcp-credentials.json ]]; then
    export GOOGLE_APPLICATION_CREDENTIALS=~/.gcp-credentials.json
  fi
fi

function cd() {
  if [[ $# == 0 ]]; then
    builtin cd ~ && ls
  else
    builtin cd "$*" && ls
  fi
}

[[ -f ~/.bashrc.local ]] && source ~/.bashrc.local

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  export _JAVA_AWT_WM_NONREPARENTING=1 # XMonad + AWT
  exec ssh-agent startx
fi
