#!/usr/bin/env bash

xrdb -merge ~/.Xresources

xsetroot -cursor_name 'left_ptr'
xsetroot -solid "$THEME_BACKGROUND"
hsetroot -solid "$THEME_BACKGROUND"
xcompmgr & # fix border redraw issue

setxkb poskeys

# power saving off
xset -dpms &
xset s noblank &
xset s off &

# rxvt daemon
urxvtd -q -f -o

# autohide mouse cursor
unclutter -root -idle 5 &

/usr/bin/VBoxClient-all

exec xmonad
