#!/usr/bin/env bash

xrdb -merge ~/.Xresources

xsetroot -cursor_name 'left_ptr'
xsetroot -solid "$THEME_BACKGROUND"
hsetroot -solid "$THEME_BACKGROUND"

# See /usr/share/X11/xkb/symbols/custom
setxkbmap custom

urxvtd -q -f -o

# autohide mouse cursor
unclutter -root -idle 5 &

xcape -e 'Control_L=Escape;Super_L=Tab'

[[ -x /usr/bin/VBoxClient-all ]] && /usr/bin/VBoxClient-all

exec xmonad
