- name: Create {{ version }} folder
  file:
    path: "{{ share_dir }}/delta/{{ version }}"
    state: directory
  tags: [delta]

- name: Fetch {{ version }} deb
  get_url:
    url: "https://github.com/dandavison/delta/releases/download/{{ version }}/git-delta_{{ version }}_amd64.deb"
    dest: "{{ share_dir }}/delta/{{ version }}/delta.deb"
  tags: [delta]

- name: Install {{ version }} deb
  become: yes
  apt:
    deb: "{{ share_dir }}/delta/{{ version }}/delta.deb"
  tags: [delta]
