- name: Install VirtualBox guest packages
  become: yes
  become_user: root
  pacman:
    name: '{{item}}'
    state: present
  with_items:
    - virtualbox-guest-modules-arch
    - virtualbox-guest-utils

- name: Add user to VirtualBox shared folder group
  become: yes
  become_user: root
  user:
    name: '{{username}}'
    groups: vboxsf
    append: yes
  tags: [virtualbox, groups]

- name: Start VirtualBox guest service
  become: yes
  become_user: root
  systemd:
    name: vboxservice
    enabled: yes
  tags: [virtualbox, services]
