- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ share_dir }}/iosevka/{{ version }}"
    - "{{ share_dir }}/iosevka-fixed/{{ version }}"
    - "{{ share_dir }}/iosevka-term/{{ version }}"
    - ~/.local/share/fonts
  tags: [iosevka]

- name: Fetch and unpack {{ version }}
  unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v{{ version }}/ttf-iosevka-{{ version }}.zip
    dest: "{{ share_dir }}/iosevka/{{ version }}"
    remote_src: yes
    creates: "{{ share_dir }}/iosevka/{{ version }}/iosevka-regular.ttf"
  tags: [iosevka]

- name: Symlink Iosevka {{ version }} folder
  file:
    src: "{{ share_dir }}/iosevka/{{ version }}"
    dest: ~/.local/share/fonts/iosevka
    state: link
  tags: [iosevka]

- name: Fetch and unpack Fixed {{ version }}
  unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v{{ version }}/ttf-iosevka-fixed-{{ version }}.zip
    dest: "{{ share_dir }}/iosevka-fixed/{{ version }}"
    remote_src: yes
    creates: "{{ share_dir }}/iosevka-fixed/{{ version }}/iosevka-fixed-regular.ttf"
  tags: [iosevka]

- name: Symlink Fixed {{ version }} folder
  file:
    src: "{{ share_dir }}/iosevka-fixed/{{ version }}"
    dest: ~/.local/share/fonts/iosevka-fixed
    state: link
  tags: [iosevka]

- name: Fetch and unpack Term {{ version }}
  unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v{{ version }}/ttf-iosevka-term-{{ version }}.zip
    dest: "{{ share_dir }}/iosevka-term/{{ version }}"
    remote_src: yes
    creates: "{{ share_dir }}/iosevka-term/{{ version }}/iosevka-term-regular.ttf"
  tags: [iosevka]

- name: Symlink Term {{ version }} folder
  file:
    src: "{{ share_dir }}/iosevka-term/{{ version }}"
    dest: ~/.local/share/fonts/iosevka-term
    state: link
  tags: [iosevka]
