#!/usr/bin/env bash

set -e

selected_key=$(cat ~/.clipmenu/*.json | jq -r 'keys | .[]' | pmenu)

selected_value=$(cat ~/.clipmenu/*.json | jq -rs "add | .[\"${selected_key}\"]")

echo -n "$selected_value" | xclip -i -selection clipboard
