#!/usr/bin/env bash

usage() {
  echo 'Usage: tldr <cmd>' 1>&2
}

find_platforms() {
  curl -s https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/index.json \
    | jq --raw-output ".commands | .[] | select(.name == \"${cmd}\") | .platform | .[]"
}

prettify_output() {
  sed 's/^`/    /' | sed 's/`//g' | sed 's/^> //'
}

cmd=$1

[[ $cmd ]] || { usage; exit 1; }

platforms=$(find_platforms)

for platform in $platforms; do
   curl -s "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/${platform}/${cmd}.md"
done | prettify_output
