- name: Install snap from channel {{snap_channel}}
  become: yes
  command: snap install node --classic --channel={{snap_channel}}
  args:
    creates: /snap/bin/node
  tags: [nodejs]

- name: Install NPM packages
  become: yes
  npm:
    name: '{{item}}'
    global: yes
    state: present
  with_items:
    - yarn
    - create-react-app
    # TypeScript
    - ts-protoc-gen
  tags: [nodejs]
