- name: Add PPA
  become: yes
  apt_repository:
    repo: ppa:phoerious/keepassxc
    update_cache: yes
  tags: [keepassxc]

- name: Install APT packages
  become: yes
  apt:
    name:
      - keepassxc
    state: latest
  tags: [keepassxc]
