- name: Add PPA
  become: yes
  apt_repository:
    repo: ppa:gophers/archive
    update_cache: yes
  tags: [dev_golang]

- name: Install APT packages
  become: yes
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - golang-1.10-go
    - go-dep
  tags: [dev_golang]

- name: Install Go packages
  shell: go get {{item}}
  args:
    creates: '{{ansible_env.HOME}}/go/src/{{item}}'
  environment:
    GOPATH: '{{ansible_env.HOME}}/go'
    GOROOT: /usr/lib/go-1.10
  loop:
    - golang.org/x/tools/cmd/goimports
    - google.golang.org/grpc
    - github.com/golang/protobuf/protoc-gen-go
    - github.com/golang/dep/cmd/dep
    - github.com/golang/mock/gomock
    - github.com/golang/mock/mockgen
  tags: [dev_golang]

- name: Add startup config
  copy:
    content: |
      export GOROOT=/usr/lib/go-1.10
      export GOPATH=$HOME/go
      export PATH=$GOPATH/bin:$PATH
      export PATH=$GOROOT/bin:$PATH
    dest: '{{startup_dir}}/dev_golang'
  tags: [dev_golang]

- name: Install JetBrains Goland IDE
  become: yes
  command: snap install goland --classic
  args:
    creates: /snap/bin/goland
  tags: [dev_golang]
