- name: Create IDE folder
  file:
    path: '{{share_dir}}/arduino'
    state: directory
  tags: [arduino]

- name: Fetch and unpack IDE {{ide_version}}
  unarchive:
    src: 'https://downloads.arduino.cc/arduino-{{ide_version}}-linux64.tar.xz'
    dest: '{{share_dir}}/arduino'
    creates: '{{share_dir}}/arduino/arduino-{{ide_version}}/arduino'
    remote_src: yes
  tags: [arduino]

- name: Symlink IDE binary
  file:
    src: '{{share_dir}}/arduino/arduino-{{ide_version}}/arduino'
    dest: '{{bin_dir}}/arduino'
    state: link
  tags: [arduino]

- name: Install IDE shortcuts
  shell: '{{share_dir}}/arduino/arduino-{{ide_version}}/install.sh'
  args:
    creates: ~/.local/share/icons/hicolor/128x128/apps/arduino-arduinoide.png
  tags: [arduino]
