#!/usr/bin/env bash

export TERM='screen-256color'

export EDITOR='vim'

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;34'

export HISTCONTROL='ignoredups'
export HISTSIZE=100000

unset MAILCHECK

shopt -s histappend
shopt -s extglob

stty -ixon # disable XON/XOFF flow control

bind Space:magic-space

alias xi='xclip -selection clipboard -i'

source ~/.bash/theme.bash

if [[ $OSTYPE =~ ^linux ]]; then
  alias ls='ls --color=auto --classify'
fi

if [[ -d ~/.bin ]]; then
  export PATH=~/.bin:${PATH}
fi

if [[ -d ~/.cabal/bin ]]; then
  export PATH=~/.cabal/bin:${PATH}
fi

if [[ -d ~/.rbenv/bin ]]; then
  export PATH=~/.rbenv/bin:${PATH}
fi

if [[ -f ~/.rbenv/bin/rbenv ]]; then
  eval "$(rbenv init -)"
fi

if [[ -d ~/software/maven/apache-maven-3.3.3 ]]; then
  export M2_HOME=~/software/maven/apache-maven-3.3.3
fi

if [[ -f /etc/bash_completion ]]; then
  source /etc/bash_completion
fi

if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi

if [[ -d ~/software/google-cloud-sdk/google-cloud-sdk ]]; then
  source ~/software/google-cloud-sdk/google-cloud-sdk/path.bash.inc
  source ~/software/google-cloud-sdk/google-cloud-sdk/completion.bash.inc
fi

function cd() {
  if [[ $# == 0 ]]; then
    builtin cd ~ && ls
  else
    builtin cd "$*" && ls
  fi
}

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  export _JAVA_AWT_WM_NONREPARENTING=1 # XMonad + AWT
  exec ssh-agent startx
fi
