#!/usr/bin/env bash

if [[ $OSTYPE =~ ^linux ]]; then
  alias ls='ls --color=auto --classify'
fi

export TERM='screen-256color'

if [[ -d ~/.bin ]]; then
  export PATH=${HOME}/.bin:${PATH}
fi

if [[ -d ~/.cabal/bin ]]; then
  export PATH=${HOME}/.cabal/bin:${PATH}
fi

if [[ -d ~/.rbenv/bin ]]; then
  export PATH=${PATH}:${HOME}/.rbenv/bin
fi

if [[ -d ~/software/maven/apache-maven-3.3.3 ]]; then
  export M2_HOME=$HOME/software/maven/apache-maven-3.3.3
fi

export EDITOR='vim'

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;34'

export HISTCONTROL='ignoredups'
export HISTSIZE=100000

unset MAILCHECK

shopt -s histappend
shopt -s extglob

bind Space:magic-space

alias xi='xclip -selection clipboard -i'

source ~/.bash/theme.bash

function cd() {
  if [[ $# == 0 ]]; then
    builtin cd "$HOME" && ls
  else
    builtin cd "$*" && ls
  fi
}

if [[ -f /etc/bash_completion ]]; then
  source /etc/bash_completion
fi

if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi

if [[ -f ~/.rbenv/bin/rbenv ]]; then
  eval "$(rbenv init -)"
fi

if [[ -f ~/.nvm/nvm.sh ]]; then
  source ~/.nvm/nvm.sh
fi

if [[ -d ~/software/google-cloud-sdk/google-cloud-sdk ]]; then
  source ~/software/google-cloud-sdk/google-cloud-sdk/path.bash.inc
  source ~/software/google-cloud-sdk/google-cloud-sdk/completion.bash.inc
fi

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  export _JAVA_AWT_WM_NONREPARENTING=1 # XMonad + AWT
  exec ssh-agent startx
fi
