- name: Create resin-cli {{resin_cli_version}} folder
  file:
    path: '{{share_dir}}/resin-cli/{{resin_cli_version}}'
    state: directory
  tags: [resin_io]

- name: Fetch and unpack resin-cli {{resin_cli_version}}
  unarchive:
    src: https://github.com/resin-io/resin-cli/releases/download/v{{resin_cli_version}}/resin-cli-v{{resin_cli_version}}-linux-x64.zip
    dest: '{{share_dir}}/resin-cli/{{resin_cli_version}}'
    remote_src: yes
    creates: '{{share_dir}}/resin-cli/{{resin_cli_version}}/resin-cli/resin'
  tags: [resin_io]

- name: Symlink resin-cli {{resin_cli_version}} binary
  file:
    src: '{{share_dir}}/resin-cli/{{resin_cli_version}}/resin-cli/resin'
    dest: '{{bin_dir}}/resin'
    state: link
  tags: [resin_io]

- name: Add Etcher APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
  tags: [resin_io]

- name: Add Etcher APT repository
  become: yes
  apt_repository:
    repo: deb https://dl.bintray.com/resin-io/debian stable etcher
    state: present
    filename: etcher
    update_cache: yes
  tags: [resin_io]

- name: Install Etcher APT package
  become: yes
  apt:
    name: etcher-electron
    state: present
  tags: [resin_io]
