- name: Add PPA
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: yes
  tags: [git]

- name: Install APT packages
  become: yes
  apt:
    name:
      - git
    state: latest
  tags: [git]

- name: Install dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/.{{ item }}
  loop:
    - gitconfig
  tags: [git]

- name: Install NPM packages
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  loop:
    - diff-so-fancy
  tags: [git]

- name: Install pip3 packages
  become: yes
  pip:
    executable: pip3
    name:
      - gitlint
  tags: [git]
