" Enable Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
" Settings
Plugin 'tpope/vim-sensible'
" Colorscheme
Plugin 'jwhitley/vim-colors-solarized'
" Features
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'Valloric/ListToggle'
Plugin 'godlygeek/tabular'
" Syntax hilighting
Plugin 'rodjek/vim-puppet'
Plugin 'groenewege/vim-less'
Plugin 'autowitch/hive.vim'
Plugin 'plasticboy/vim-markdown'
Plugin 'elzr/vim-json'
Plugin 'elubow/cql-vim'
Plugin 'smerrill/vcl-vim-plugin'
Plugin 'ekalinin/Dockerfile.vim'
call vundle#end()

filetype plugin indent on

if $COLORSCHEME_TYPE == 'contrast'
  set background=light
  set nocursorline
else
  let g:solarized_termtrans=0
  set background=dark
  silent! colorscheme solarized
  set cursorline
endif

" Use normal background for line numbers
autocmd ColorScheme * highlight LineNr ctermbg=grey

" Statusline
set statusline=[%f]\ %r%=[%l,%c]\ %y\ [%{strlen(&fenc)?&fenc:'none'}]\ [%p%%]

" Config
set expandtab
set hidden
set hlsearch
set ignorecase
set nobackup
set noswapfile
set nowritebackup
set number
set shiftwidth=2
set shortmess=atI
set smartcase
set smartindent
set tabstop=2
set title
set wildignorecase
set wildmode=list:longest,full

" Keymaps
imap uu <Esc><Esc>
nnoremap <Space> <Nop>
let mapleader = " "
nnoremap <Leader>t :NERDTreeToggle<CR>
nnoremap <Leader>i gg=G<C-O><C-O>

nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>

" Plugin-based keymaps
let g:lt_quickfix_list_toggle_map = '<leader>f'

" Autocommands
autocmd BufNewFile,BufRead *.hql setf hive
autocmd BufNewFile,BufRead *.ngt setf html
autocmd BufRead *.cql set syntax=cql
autocmd FileType python set tabstop=4 expandtab shiftwidth=4 softtabstop=4

" Syntastic
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['java'] }
let g:syntastic_check_on_open = 1
let g:syntastic_enable_signs = 1
let g:syntastic_python_checkers = ['pep8', 'pyflakes']

" Markdown
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_frontmatter=1
autocmd FileType markdown setlocal textwidth=74

" NERDTree
let g:NERDTreeMinimalUI=1
let g:NERDTreeDirArrows=0
let NERDTreeIgnore = ['\.pyc$']
" Open nerdtree if vim was started without arguments
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Local rc
if filereadable('~/.vimrc.local')
  source ~/.vimrc.local
endif
