- name: Install packages
  become: yes
  apt:
    name: '{{item}}'
  loop:
    - openjdk-11-jdk-headless
    - maven
  tags: [java]

- name: Add startup config
  copy:
    content: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
    dest: '{{startup_dir}}/java'
  tags: [java]
