- name: Install Haskell packages
  become: yes
  apt:
    name:
      - haskell-stack
      - cabal-install
      - happy
      - alex
    state: latest
  tags: [haskell]

- name: Install hfmt
  shell: cabal update && cabal install hfmt
  args:
    creates: ~/.cabal/bin/hfmt
  tags: [haskell]

- name: Add startup config
  copy:
    content: export PATH=$HOME/.cabal/bin:$PATH
    dest: "{{ startup_dir }}/haskell"
  tags: [haskell]
