#!/usr/bin/env bash

export HISTCONTROL='ignoredups'
export HISTSIZE=100000
unset MAILCHECK

eval "$(dircolors -b)"
export PYTHONDONTWRITEBYTECODE='1'

# Interactive shells only
if [[ $- =~ i ]]; then
  bind Space:magic-space
  stty -ixon # disable XON/XOFF flow control
  source ~/.bash.d/prompt.bash
fi

shopt -s histappend
shopt -s extglob

alias xi='xclip -selection clipboard -i'
alias xo='xclip -selection clipboard -o'
alias less='less -R'
alias grep='grep --color=auto'
alias ls='ls --color=auto --classify'

if [[ -f /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
  if which kubectl &>/dev/null; then
    source <(kubectl completion bash)
  fi
fi

function cd() {
  if [[ $# == 0 ]]; then
    builtin cd ~ && ls
  else
    builtin cd "$*" && ls
  fi
}

[[ -f ~/.bashrc.local ]] && source ~/.bashrc.local
