- name: Create {{version}} dir
  file:
    path: '{{share_dir}}/cmpl/{{version}}'
    state: directory
  tags: [cmpl]

- name: Fetch and unpack {{version}}
  unarchive:
    src: http://www.coliop.org/_download/Cmpl-{{version}}-Linux64.tar.gz
    dest: '{{share_dir}}/cmpl/{{version}}'
    remote_src: yes
    creates: '{{share_dir}}/cmpl/{{version}}/Cmpl/cmpl'
  tags: [cmpl]

- name: Add startup config
  copy:
    content: 'export CMPLBINARY={{share_dir}}/cmpl/{{version}}/Cmpl/cmpl'
    dest: '{{startup_dir}}/cmpl'
  tags: [cmpl]
