- name: Install APT packages
  become: yes
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - curl
    - httpie
  tags: [dev]

- name: Install Ruby gems
  become: yes
  gem:
    name: '{{item}}'
    user_install: no
  with_items:
    - mdl # lint markdown
  tags: [dev]

- name: Install Python 3 packages
  become: yes
  pip:
    name: '{{item}}'
    executable: pip3
  with_items:
    - proselint # lint documentation
  tags: [dev]

- name: Install NPM packages
  become: yes
  npm:
    name: '{{item}}'
    global: yes
    state: present
  with_items:
    - sloc # count code
  tags: [dev]
