#!/usr/bin/env bash

set -e

usage() {
  {
    echo 'Usage:'
    echo '  tmuxssh [HOSTNAME...]'
    echo
    echo 'Examples:'
    echo '  tmuxssh localhost{,,}'
    echo '  echo localhost{,,} | tmuxssh'
  } 2>&1
}

if [[ ! -t 0 ]]; then
  hostnames=($(xargs))
else
  hostnames=("$@")
fi

[[ ${#hostnames[@]} -gt 0 ]] || {
  usage
  exit 1
}

tmux new-window -a "ssh ${hostnames[0]}"
tmux rename-window "tmuxssh ${hostnames[0]:0:20}..."
for server in "${hostnames[@]:1}"; do
  tmux split-window "ssh ${server}; [[ "'$?'" == 255 ]] && echo 'Failed to connect to ${server}' && read"
  tmux select-layout tiled
done
