#!/usr/bin/env bash
#
# Set a keyboard layout from ~/.xkb

set -e

usage() {
  echo "Usage: setxkb <layout-name>"
}

layout_name=$1
[[ -n "${layout_name}" ]] || { usage; exit 1; }

setxkbmap -I "$HOME/.xkb" "$layout_name" -print | xkbcomp -I"$HOME/.xkb" - "$DISPLAY"
