#!/usr/bin/env bash

xrdb -merge ~/.Xresources

xsetroot -cursor_name 'left_ptr'
xsetroot -solid "$COLORSCHEME_DARK_GRAY"
hsetroot -solid "$COLORSCHEME_DARK_GRAY"
xcompmgr & # fix border redraw issue

setxkb poskeys

# power saving off
xset -dpms &
xset s noblank &
xset s off &

# rxvt daemon
urxvtd -q -f -o

VBoxClient --clipboard

# autohide mouse cursor
unclutter -root -idle 5 &

exec xmonad
