- name: Add APT key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  tags: [google_chrome]

- name: Add APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
    update_cache: yes
  tags: [google_chrome]

- name: Install APT package
  become: yes
  apt:
    name: google-chrome-stable
    state: present
  tags: [google_chrome]
