- name: Install APT packages
  become: yes
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - ruby
    - ruby-dev
  tags: [ruby]

- name: Install dotfiles
  copy:
    src: '{{item}}'
    dest: ~/.{{item}}
  loop:
    - gemrc
  tags: [ruby]
